"""Python mirror of the redRover firmware wire protocol.

This is the counterpart to ``firmware/lib/RedRover/src/redrover/Protocol.h``
and must stay byte-compatible with it. ``tests/test_wire.py`` checks that with
golden frames generated by the C++ implementation itself, so a change on
either side that breaks the other fails the suite rather than the robot.

Frame layout, before COBS encoding::

    +-----+------+-----+-----+----------+---------+
    | ver | type | seq | len | payload  | crc16   |
    |  1  |  1   |  1  |  1  |   len    |    2    |
    +-----+------+-----+-----+----------+---------+

The CRC covers ver..payload. Multi-byte fields are little-endian.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass, field
from enum import IntEnum

PROTOCOL_VERSION = 1
HEADER_LEN = 4
CRC_LEN = 2
DELIMITER = 0x00


class MsgType(IntEnum):
    # Host -> device
    HELLO = 0x01
    DESCRIBE = 0x02
    SET_STREAM = 0x03
    DRIVE = 0x04
    DRIVE_RAW = 0x05
    STOP = 0x06
    ESTOP = 0x07
    SET_AUX = 0x08
    PING = 0x09
    READ_ONCE = 0x0A

    # Device -> host
    HELLO_ACK = 0x81
    DESCRIPTOR = 0x82
    SAMPLE = 0x83
    STATUS = 0x85
    LOG = 0x86
    ACK = 0x87


class AckCode(IntEnum):
    OK = 0
    UNKNOWN_TYPE = 1
    BAD_LENGTH = 2
    REJECTED = 3
    NOT_SUPPORTED = 4
    ESTOP_ACTIVE = 5


class SensorKind(IntEnum):
    GENERIC = 0
    ACCELERATION = 1
    ANGULAR_RATE = 2
    MAGNETIC = 3
    DISTANCE = 4
    TEMPERATURE = 5
    HUMIDITY = 6
    PRESSURE = 7
    SOUND = 8
    LIGHT = 9
    VOLTAGE = 10
    CURRENT = 11
    GAS = 12
    ENCODER = 13
    BUMPER = 14
    ODOMETRY = 15
    BATTERY = 16
    CUSTOM = 200


class Unit(IntEnum):
    NONE = 0
    METRE_PER_SECOND2 = 1
    DEGREE_PER_SECOND = 2
    METRE = 3
    CELSIUS = 4
    PERCENT = 5
    PASCAL = 6
    VOLT = 7
    AMPERE = 8
    TESLA = 9
    LUX = 10
    COUNT = 11
    PARTS_PER_MILLION = 12
    DEGREE = 13
    BOOLEAN = 14


class NodeState(IntEnum):
    BOOTING = 0
    IDLE = 1
    DRIVING = 2
    EMERGENCY_STOP = 3
    FAULT = 4


class LogLevel(IntEnum):
    DEBUG = 0
    INFO = 1
    WARN = 2
    ERROR = 3


class ProtocolError(ValueError):
    """A frame could not be decoded."""


# ---------------------------------------------------------------------------
# CRC-16/CCITT-FALSE
# ---------------------------------------------------------------------------


def crc16(data: bytes) -> int:
    crc = 0xFFFF
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


# ---------------------------------------------------------------------------
# COBS
# ---------------------------------------------------------------------------


def cobs_encode(data: bytes) -> bytes:
    """Encode so that no 0x00 appears in the result."""
    out = bytearray()
    code_index = 0
    out.append(0)  # placeholder for the first code byte
    code = 1

    for byte in data:
        if byte == 0:
            out[code_index] = code
            code = 1
            code_index = len(out)
            out.append(0)
            continue
        out.append(byte)
        code += 1
        if code == 0xFF:
            out[code_index] = code
            code = 1
            code_index = len(out)
            out.append(0)

    out[code_index] = code
    return bytes(out)


def cobs_decode(data: bytes) -> bytes:
    """Decode a delimiter-free COBS frame."""
    out = bytearray()
    index = 0
    length = len(data)

    while index < length:
        code = data[index]
        if code == 0:
            raise ProtocolError("zero code byte inside a COBS frame")
        index += 1
        end = index + code - 1
        if end > length:
            raise ProtocolError("COBS run overruns the frame")
        out.extend(data[index:end])
        index = end
        if code != 0xFF and index < length:
            out.append(0)

    return bytes(out)


# ---------------------------------------------------------------------------
# Frames
# ---------------------------------------------------------------------------


@dataclass
class Frame:
    type: MsgType
    seq: int = 0
    payload: bytes = b""

    def encode(self) -> bytes:
        """Serialise to the wire, COBS-encoded with a trailing delimiter."""
        if len(self.payload) > 255:
            raise ProtocolError(f"payload of {len(self.payload)} bytes exceeds 255")
        body = (
            bytes([PROTOCOL_VERSION, int(self.type), self.seq & 0xFF, len(self.payload)])
            + self.payload
        )
        raw = body + struct.pack("<H", crc16(body))
        return cobs_encode(raw) + bytes([DELIMITER])

    @classmethod
    def decode(cls, encoded: bytes) -> Frame:
        """Parse one delimiter-free COBS frame."""
        raw = cobs_decode(encoded)
        if len(raw) < HEADER_LEN + CRC_LEN:
            raise ProtocolError(f"frame too short: {len(raw)} bytes")
        version, msg_type, seq, length = raw[0], raw[1], raw[2], raw[3]
        if version != PROTOCOL_VERSION:
            raise ProtocolError(f"protocol version {version}, expected {PROTOCOL_VERSION}")
        if len(raw) != HEADER_LEN + length + CRC_LEN:
            raise ProtocolError("declared length does not match frame size")

        body = raw[: HEADER_LEN + length]
        (want_crc,) = struct.unpack("<H", raw[HEADER_LEN + length :])
        if crc16(body) != want_crc:
            raise ProtocolError("CRC mismatch")

        try:
            parsed_type = MsgType(msg_type)
        except ValueError as exc:
            raise ProtocolError(f"unknown message type 0x{msg_type:02X}") from exc

        return cls(type=parsed_type, seq=seq, payload=body[HEADER_LEN:])


class FrameReader:
    """Incremental reassembler for a byte stream.

    Feed it whatever arrives; it yields complete frames. A run longer than any
    legal frame is discarded at the next delimiter rather than growing without
    bound, which is what keeps a noisy link from exhausting memory.
    """

    def __init__(self, max_frame: int = 512):
        self.max_frame = max_frame
        self._buffer = bytearray()
        self._overflow = False
        self.dropped = 0

    def feed(self, data: bytes) -> list[Frame]:
        frames: list[Frame] = []
        for byte in data:
            if byte == DELIMITER:
                if self._overflow:
                    self.dropped += 1
                elif self._buffer:
                    try:
                        frames.append(Frame.decode(bytes(self._buffer)))
                    except ProtocolError:
                        self.dropped += 1
                self._buffer.clear()
                self._overflow = False
                continue
            if len(self._buffer) >= self.max_frame:
                self._overflow = True
                continue
            self._buffer.append(byte)
        return frames


# ---------------------------------------------------------------------------
# Payload builders and parsers
# ---------------------------------------------------------------------------


def drive_payload(linear_mm_s: int, angular_mrad_s: int, lateral_mm_s: int = 0) -> bytes:
    """Build a Drive payload.

    Angular velocity is milliradians per second — see the note in Types.h:
    millidegrees in an int16 would cap the robot at 32.7 deg/s.
    """
    return struct.pack("<hhh", int(linear_mm_s), int(angular_mrad_s), int(lateral_mm_s))


def drive_raw_payload(left_per_mil: int, right_per_mil: int) -> bytes:
    return struct.pack("<hh", int(left_per_mil), int(right_per_mil))


def set_stream_payload(rate_hz: int, enabled_mask: int = 0xFFFFFFFF) -> bytes:
    return struct.pack("<HI", int(rate_hz), int(enabled_mask) & 0xFFFFFFFF)


def set_aux_payload(channel: int, value: int) -> bytes:
    return struct.pack("<Bh", int(channel) & 0xFF, int(value))


@dataclass
class HelloAck:
    protocol_version: int
    sensor_count: int
    holonomic: bool
    max_linear_mm_s: int
    max_angular_mrad_s: int
    command_timeout_ms: int
    board: str

    @classmethod
    def parse(cls, payload: bytes) -> HelloAck:
        if len(payload) < 9:
            raise ProtocolError("short HelloAck")
        version, count, holonomic = payload[0], payload[1], payload[2]
        max_linear, max_angular, timeout = struct.unpack("<HHH", payload[3:9])
        board = payload[9:].split(b"\x00", 1)[0].decode("ascii", "replace")
        return cls(version, count, bool(holonomic), max_linear, max_angular, timeout, board)


@dataclass
class SensorDescriptor:
    id: int
    kind: SensorKind
    unit: Unit
    channels: int
    scale_exp: int
    rate_hz: int
    failed: bool
    name: str

    @property
    def scale(self) -> float:
        """Multiply a raw integer value by this to get the physical value."""
        return 10.0**self.scale_exp

    def to_physical(self, raw: int) -> float:
        return raw * self.scale

    @classmethod
    def parse(cls, payload: bytes) -> SensorDescriptor:
        if len(payload) < 8:
            raise ProtocolError("short Descriptor")
        sensor_id, kind, unit, channels = payload[0], payload[1], payload[2], payload[3]
        scale_exp = struct.unpack("<b", payload[4:5])[0]
        (rate_hz,) = struct.unpack("<H", payload[5:7])
        failed = bool(payload[7])
        name = payload[8:].split(b"\x00", 1)[0].decode("ascii", "replace")
        return cls(
            id=sensor_id,
            kind=SensorKind(kind) if kind in SensorKind._value2member_map_ else SensorKind.CUSTOM,
            unit=Unit(unit) if unit in Unit._value2member_map_ else Unit.NONE,
            channels=channels,
            scale_exp=scale_exp,
            rate_hz=rate_hz,
            failed=failed,
            name=name,
        )


@dataclass
class Sample:
    sensor_id: int
    timestamp_ms: int
    values: list[int] = field(default_factory=list)

    @classmethod
    def parse(cls, payload: bytes) -> Sample:
        if len(payload) < 6:
            raise ProtocolError("short Sample")
        sensor_id = payload[0]
        (timestamp_ms,) = struct.unpack("<I", payload[1:5])
        channels = payload[5]
        expected = 6 + channels * 4
        if len(payload) < expected:
            raise ProtocolError("Sample truncated")
        values = list(struct.unpack(f"<{channels}i", payload[6:expected]))
        return cls(sensor_id=sensor_id, timestamp_ms=timestamp_ms, values=values)


@dataclass
class Status:
    state: NodeState
    estop: bool
    battery_mv: int
    uptime_ms: int
    dropped_frames: int

    @classmethod
    def parse(cls, payload: bytes) -> Status:
        if len(payload) < 10:
            raise ProtocolError("short Status")
        state = payload[0]
        estop = bool(payload[1])
        battery_mv, uptime_ms, dropped = struct.unpack("<HIH", payload[2:10])
        return cls(
            state=NodeState(state) if state in NodeState._value2member_map_ else NodeState.FAULT,
            estop=estop,
            battery_mv=battery_mv,
            uptime_ms=uptime_ms,
            dropped_frames=dropped,
        )


@dataclass
class Ack:
    of_type: int
    code: AckCode

    @property
    def ok(self) -> bool:
        return self.code is AckCode.OK

    @classmethod
    def parse(cls, payload: bytes) -> Ack:
        if len(payload) < 2:
            raise ProtocolError("short Ack")
        code = payload[1]
        return cls(
            of_type=payload[0],
            code=AckCode(code) if code in AckCode._value2member_map_ else AckCode.REJECTED,
        )


@dataclass
class LogMessage:
    level: LogLevel
    text: str

    @classmethod
    def parse(cls, payload: bytes) -> LogMessage:
        if not payload:
            raise ProtocolError("short Log")
        level = payload[0]
        return cls(
            level=LogLevel(level) if level in LogLevel._value2member_map_ else LogLevel.INFO,
            text=payload[1:].decode("ascii", "replace"),
        )
